events {}

http {
    server {
        listen 8080;

        location / {
            proxy_pass http://oncall-engine:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # Вот эти два заголовка решают проблему 403
            proxy_set_header X-Oncall-Stack-Id "1";
            proxy_set_header X-Oncall-Org-Id "1";
        }
    }
}